name: build-windows
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_job:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@master
      with:
        node-version: 20
    - name: install dependencies electron-app
      run: npm install
      working-directory: electron-app

    - name: install dependencies server
      run: npm install
      working-directory: server

    - name: lint/format electron-app
      env:
        CI: false
      run: npm run ci:format
      working-directory: electron-app

    - name: lint/format server
      env:
        CI: false
      run: npm run ci:format
      working-directory: server

    - name: test
      env:
        CI: false
      run: npm run test
      working-directory: server

    - name: compile server
      env:
        CI: false
      run: npm run compile
      working-directory: server

    - name: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        CERTIFICATE_CONTAINER_ID: ${{ secrets.CERTIFICATE_CONTAINER_ID }}
        CERTIFICATE_READER: ${{ secrets.CERTIFICATE_READER }}
      run: |
        Copy-Item server/src electron-app/src/sync-agent -r
        npm run make-win
        'C:/Program Files (x86)/Windows Kits/10/bin/10.0.22621.0/x86/signtool.exe' sign /tr http://timestamp.digicert.com /td sha256 /fd sha256 /f C:\Users\user\Documents\certificat_nuclia.cer /csp "eToken Base Cryptographic Provider" /kc "[$CERTIFICATE_READER{{$CERTIFICATE_PASSWORD}}]=$CERTIFICATE_CONTAINER_ID" electron-app/out/make/squirrel.windows/x64/Nuclia-Sync-Setup.exe

    - name: Release Windows installer
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v0.0.2
        files: |
          out/make/*.exe
          out/make/*.exe.blockmap
          out/make/*.yml