name: build-windows
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_job:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@master
      with:
        node-version: 20
    - name: install dependencies electron-app
      run: npm install
      working-directory: electron-app

    - name: install dependencies server
      run: npm install
      working-directory: server

    - name: lint/format electron-app
      env:
        CI: false
      run: npm run ci:format
      working-directory: electron-app

    - name: lint/format server
      env:
        CI: false
      run: npm run ci:format
      working-directory: server

    - name: test
      env:
        CI: false
      run: npm run test
      working-directory: server

    - name: compile server
      env:
        CI: false
      run: npm run compile
      working-directory: server

    - name: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        Copy-Item server/src electron-app/src/sync-agent -r
        npm run publish-win