name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_job:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@master
      with:
        node-version: 20
    - name: install dependencies
      run: npm install
      working-directory: electron-app

    - name: install dependencies
      run: npm install
      working-directory: server

    - name: lint/format
      env:
        CI: false
      run: npm run ci:format
      working-directory: electron-app

    - name: lint/format
      env:
        CI: false
      run: npm run ci:format
      working-directory: server

    - name: test
      env:
        CI: false
      run: npm run test
      working-directory: server

    - name: build
      env:
        CI: false
      run: npm run make
      working-directory: electron-app