name: test
on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@master
        with:
          node-version: 20
      - name: install dependencies electron-app
        run: npm install
        working-directory: electron-app

      - name: install dependencies server
        run: npm install
        working-directory: server

      - name: lint/format electron-app
        env:
          CI: false
        run: npm run ci:format
        working-directory: electron-app

      - name: lint/format server
        env:
          CI: false
        run: npm run ci:format
        working-directory: server

      - name: test
        env:
          CI: false
        run: npm run test
        working-directory: server


  build_job_windows:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GHAPP_ID_NUCLIABOT }}
          private-key: ${{ secrets.PK_GHAPP_NUCLIABOT_ORG }}
          owner: nuclia

      - name: Trigger Windows Release
        uses: the-actions-org/workflow-dispatch@v4
        id: invoke-windows-release
        with:
          workflow: release-windows-sync-agent
          repo: nuclia/core-apps
          token: ${{ steps.app-token.outputs.token }}
          wait-for-completion: true
          inputs: '{"release_tag": "${{ needs.pre-release.outputs.release-tag }}"}'
